package nativeharnessclient

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"regexp"
	"strconv"
	"time"
	"unicode"
	"unicode/utf8"

	modulecore "github.com/Nyukimin/RenCrow_CORE/modules/core"
)

const (
	originProofDomain = "rencrow-origin-proof/v1\x00"
	// originHuman is the only origin CORE signs: a relay of the user's own
	// input. Requests generated by CORE itself carry no proof (Automation).
	originHuman = "human"
	// maxProofTTLSeconds is the longest proof lifetime allowed by the 07 section.
	maxProofTTLSeconds = 300
	maxNonceBytes      = 128
	nonceRandomBytes   = 16
	proofTimeLayout    = "2006-01-02T15:04:05Z"
)

var (
	// ErrInvalidIssuerSettings reports issuer settings, key, clock or nonce
	// source that cannot be used to sign.
	ErrInvalidIssuerSettings = errors.New("invalid origin proof issuer settings")
	// ErrInvalidOriginRequest reports a request (or an issued nonce or time)
	// that cannot be signed. Nothing is signed.
	ErrInvalidOriginRequest = errors.New("invalid origin proof request")
	// ErrOriginRecordMismatch reports text that is not byte-identical to the
	// raw input of the accepted record. Nothing is signed.
	ErrOriginRecordMismatch = errors.New("text does not match the accepted raw input")
)

// principalPattern is the principal grammar of the 04 delegation section.
var principalPattern = regexp.MustCompile(`^[a-z][a-z0-9_-]{0,31}:[A-Za-z0-9][A-Za-z0-9._-]{0,63}$`)

// Clock supplies the issuing time. It is injected so tests are deterministic.
type Clock interface{ Now() time.Time }

// NonceSource supplies a fresh nonce for each proof.
type NonceSource interface{ NewNonce() (string, error) }

// SystemClock is the production Clock.
type SystemClock struct{}

// Now returns the current time.
func (SystemClock) Now() time.Time { return time.Now() }

// RandNonceSource is the production NonceSource: 16 bytes from crypto/rand as
// 32 lowercase hex characters. A failure of the entropy source is returned,
// never replaced by another source.
type RandNonceSource struct{}

// NewNonce returns a fresh random nonce.
func (RandNonceSource) NewNonce() (string, error) {
	var random [nonceRandomBytes]byte
	if _, err := rand.Read(random[:]); err != nil {
		return "", fmt.Errorf("read random nonce: %w", err)
	}
	return hex.EncodeToString(random[:]), nil
}

// IssuerSettings are the logical items of the 05 issuer configuration except
// the key file, which is read by LoadKeyFile. The CORE configuration section
// native_harness.issuer owns the file paths and builds these settings.
type IssuerSettings struct {
	Issuer     string
	KeyID      string
	Audience   string
	TTLSeconds int
}

// AcceptedInput is the record of an input CORE accepted from the user, as
// read from the CORE acceptance store. The caller must build it from that
// store in the same function that asks for the proof, and only for a message
// whose author is the authenticated user; it must never be built from model
// output, a summary or Agent generated text. This package can check that the
// text equals Raw, but it cannot prove who authored the record.
type AcceptedInput struct {
	MessageID modulecore.MessageID
	ThreadID  modulecore.ThreadID
	// Sequence is the acceptance sequence of the record.
	Sequence uint64
	// Raw is the original input bytes (UTF-8) exactly as accepted.
	Raw []byte
}

// OriginProofRequest asks for the proof of one relay. The source message,
// source thread and sequence come only from Accepted; the request has no
// separate source fields and no origin.
type OriginProofRequest struct {
	// Text is the relayed input. It must be byte-identical to Accepted.Raw.
	Text     string
	Accepted AcceptedInput
	// DestinationThreadID is the Harness thread of the API request. The
	// Harness owns it, so it is a string checked against the canonical ID
	// grammar, not a CORE ID type.
	DestinationThreadID string
	// MutationKey is the idempotency key of the API request.
	MutationKey string
}

// OriginProof is the proof value placed in the relayed input. The field order
// is the MAC order of the 07 section; Mac is last and not part of its input.
type OriginProof struct {
	Issuer              string `json:"issuer"`
	KeyID               string `json:"key_id"`
	Audience            string `json:"audience"`
	Origin              string `json:"origin"`
	SourceMessageID     string `json:"source_message_id"`
	SourceThreadID      string `json:"source_thread_id"`
	DestinationThreadID string `json:"destination_thread_id"`
	MutationKey         string `json:"mutation_key"`
	RawHash             string `json:"raw_hash"`
	Sequence            uint64 `json:"sequence"`
	IssuedAt            string `json:"issued_at"`
	ExpiresAt           string `json:"expires_at"`
	Nonce               string `json:"nonce"`
	MAC                 string `json:"mac"`
}

// OriginSigner issues OriginProofs. It is safe for concurrent use. A proof
// must be created once per new idempotency key; a retry with the same key
// reuses the first proof and never calls Sign again.
type OriginSigner struct {
	settings IssuerSettings
	// key is a pointer so default formatting of a signer cannot print bytes.
	key    *Key
	clock  Clock
	nonces NonceSource
}

// Validate reports whether the settings can issue proofs: issuer and key_id
// are non-empty UTF-8 without control characters, the audience is a
// principal, and ttl_seconds is 1..300. Every violation is an
// ErrInvalidIssuerSettings. NewOriginSigner and the CORE configuration check
// use this one rule.
func (s IssuerSettings) Validate() error {
	if !isPlainIdentifier(s.Issuer) {
		return fmt.Errorf("%w: issuer must be non-empty UTF-8 without control characters", ErrInvalidIssuerSettings)
	}
	if !isPlainIdentifier(s.KeyID) {
		return fmt.Errorf("%w: key_id must be non-empty UTF-8 without control characters", ErrInvalidIssuerSettings)
	}
	if !principalPattern.MatchString(s.Audience) {
		return fmt.Errorf("%w: audience must be a principal", ErrInvalidIssuerSettings)
	}
	if s.TTLSeconds < 1 || s.TTLSeconds > maxProofTTLSeconds {
		return fmt.Errorf("%w: ttl_seconds must be 1..%d", ErrInvalidIssuerSettings, maxProofTTLSeconds)
	}
	return nil
}

// NewOriginSigner validates the settings and returns a signer.
func NewOriginSigner(settings IssuerSettings, key Key, clock Clock, nonces NonceSource) (*OriginSigner, error) {
	if err := settings.Validate(); err != nil {
		return nil, err
	}
	if key.isZero() {
		return nil, fmt.Errorf("%w: key is not loaded", ErrInvalidIssuerSettings)
	}
	if clock == nil || nonces == nil {
		return nil, fmt.Errorf("%w: clock and nonce source are required", ErrInvalidIssuerSettings)
	}
	return &OriginSigner{settings: settings, key: &key, clock: clock, nonces: nonces}, nil
}

// Sign returns the proof of one relay. Every check runs before the clock and
// the nonce source are used, and on any failure the zero proof is returned.
// The raw_hash is the SHA-256 of Text; Accepted.Raw is used only for the
// equality check, so later changes to Raw cannot alter the issued proof.
func (s *OriginSigner) Sign(request OriginProofRequest) (OriginProof, error) {
	if err := validateOriginRequest(request); err != nil {
		return OriginProof{}, err
	}
	if string(request.Accepted.Raw) != request.Text {
		return OriginProof{}, ErrOriginRecordMismatch
	}
	now := s.clock.Now()
	if now.IsZero() {
		return OriginProof{}, fmt.Errorf("%w: clock returned the zero time", ErrInvalidOriginRequest)
	}
	issuedAt := now.UTC().Truncate(time.Second)
	expiresAt := issuedAt.Add(time.Duration(s.settings.TTLSeconds) * time.Second)
	nonce, err := s.nonces.NewNonce()
	if err != nil {
		return OriginProof{}, fmt.Errorf("issue origin proof nonce: %w", err)
	}
	if len(nonce) > maxNonceBytes || !isPlainIdentifier(nonce) {
		return OriginProof{}, fmt.Errorf("%w: nonce must be 1..%d bytes of UTF-8 without control characters", ErrInvalidOriginRequest, maxNonceBytes)
	}
	rawHash := sha256.Sum256([]byte(request.Text))
	proof := OriginProof{
		Issuer:              s.settings.Issuer,
		KeyID:               s.settings.KeyID,
		Audience:            s.settings.Audience,
		Origin:              originHuman,
		SourceMessageID:     string(request.Accepted.MessageID),
		SourceThreadID:      string(request.Accepted.ThreadID),
		DestinationThreadID: request.DestinationThreadID,
		MutationKey:         request.MutationKey,
		RawHash:             hex.EncodeToString(rawHash[:]),
		Sequence:            request.Accepted.Sequence,
		IssuedAt:            issuedAt.Format(proofTimeLayout),
		ExpiresAt:           expiresAt.Format(proofTimeLayout),
		Nonce:               nonce,
	}
	mac := hmac.New(sha256.New, s.key.bytes[:])
	mac.Write(originMACInput(proof))
	proof.MAC = hex.EncodeToString(mac.Sum(nil))
	return proof, nil
}

func validateOriginRequest(request OriginProofRequest) error {
	if request.Text == "" || !utf8.ValidString(request.Text) {
		return fmt.Errorf("%w: text must be non-empty UTF-8", ErrInvalidOriginRequest)
	}
	if err := request.Accepted.MessageID.Validate(); err != nil {
		return fmt.Errorf("%w: source message id: %v", ErrInvalidOriginRequest, err)
	}
	if err := request.Accepted.ThreadID.Validate(); err != nil {
		return fmt.Errorf("%w: source thread id: %v", ErrInvalidOriginRequest, err)
	}
	// The destination thread is Harness-owned, so only the canonical grammar
	// is checked; the CORE type is not used as that thread's identity.
	if err := modulecore.ThreadID(request.DestinationThreadID).Validate(); err != nil {
		return fmt.Errorf("%w: destination thread id: %v", ErrInvalidOriginRequest, err)
	}
	if !isPlainIdentifier(request.MutationKey) {
		return fmt.Errorf("%w: mutation key must be non-empty UTF-8 without control characters", ErrInvalidOriginRequest)
	}
	return nil
}

// originMACInput is the MAC input of the 07 section: the domain string and
// LP of the 13 fields in the fixed order, without the mac itself.
func originMACInput(proof OriginProof) []byte {
	input := make([]byte, 0, 512)
	input = append(input, originProofDomain...)
	for _, value := range []string{
		proof.Issuer,
		proof.KeyID,
		proof.Audience,
		proof.Origin,
		proof.SourceMessageID,
		proof.SourceThreadID,
		proof.DestinationThreadID,
		proof.MutationKey,
		proof.RawHash,
		strconv.FormatUint(proof.Sequence, 10),
		proof.IssuedAt,
		proof.ExpiresAt,
		proof.Nonce,
	} {
		input = appendLP(input, value)
	}
	return input
}

// isPlainIdentifier reports whether value is non-empty valid UTF-8 without
// control characters.
func isPlainIdentifier(value string) bool {
	if value == "" || !utf8.ValidString(value) {
		return false
	}
	for _, r := range value {
		if unicode.IsControl(r) {
			return false
		}
	}
	return true
}
