package orchestrator

import (
	"context"
	"errors"
	"strings"
	"testing"

	moduleapp "github.com/Nyukimin/RenCrow_CORE/internal/application/moduleregistry"
	"github.com/Nyukimin/RenCrow_CORE/internal/application/service"
	"github.com/Nyukimin/RenCrow_CORE/internal/domain/capability"
	domainmodule "github.com/Nyukimin/RenCrow_CORE/internal/domain/moduleregistry"
	"github.com/Nyukimin/RenCrow_CORE/internal/domain/patch"
	"github.com/Nyukimin/RenCrow_CORE/internal/domain/proposal"
	"github.com/Nyukimin/RenCrow_CORE/internal/domain/routing"
	domainskill "github.com/Nyukimin/RenCrow_CORE/internal/domain/skillgovernance"
	"github.com/Nyukimin/RenCrow_CORE/internal/domain/task"
)

// TestCodeExecutor_CODE1Route はCODE1明示ルートのテスト（RED）
func TestCodeExecutor_CODE1Route(t *testing.T) {
	coder1 := &mockCoderAgent{response: "CODE1 response"}
	executor := NewDefaultCodeExecutor(coder1, nil, nil, nil, nil, nil, noopEventEmitter)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE1,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}

	if resp.Response != "CODE1 response" {
		t.Errorf("Expected 'CODE1 response', got '%s'", resp.Response)
	}

	if resp.Handled {
		t.Error("CODE1 should not use Proposal path")
	}
}

// TestCodeExecutor_CODE3_WithProposal はCODE3 Proposal実行のテスト（RED）
func TestCodeExecutor_CODE3_WithProposal(t *testing.T) {
	testProposal := proposal.NewProposal(
		"Test plan",
		`[{"type": "file_edit", "action": "create", "target": "test.txt", "content": "test"}]`,
		"Low risk",
		"Low cost",
	)

	coder3 := &mockCoderAgentWithProposal{
		response: "Proposal generated",
		proposal: testProposal,
	}

	workerService := &recordingCodeWorkerExecutionService{}
	executor := NewDefaultCodeExecutor(nil, nil, coder3, nil, workerService, nil, noopEventEmitter)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE3,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}

	if !resp.Handled {
		t.Error("CODE3 with Proposal should be handled via Proposal path")
	}

	// レスポンスにPlanが含まれることを確認
	if resp.Response == "" {
		t.Error("Expected non-empty response")
	}
	if workerService.calls != 1 {
		t.Fatalf("worker ExecuteProposal calls=%d, want 1", workerService.calls)
	}
	if workerService.jobID.String() != jobID.String() {
		t.Fatalf("worker jobID=%s, want %s", workerService.jobID.String(), jobID.String())
	}
	if workerService.proposal != testProposal {
		t.Fatal("worker should receive the same proposal instance generated by coder")
	}
}

func TestCodeExecutor_CODE2_WithProposal_ExecutesPatch(t *testing.T) {
	testProposal := proposal.NewProposal(
		"Implement requested change",
		`[{"type": "file_edit", "action": "create", "target": "implemented.txt", "content": "done"}]`,
		"Low risk",
		"Low cost",
	)

	coder2 := &mockCoderAgentWithProposal{
		response: "plain response should not be used",
		proposal: testProposal,
	}

	workerService := &recordingCodeWorkerExecutionService{}
	executor := NewDefaultCodeExecutor(nil, coder2, nil, nil, workerService, nil, noopEventEmitter)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "README.md を更新して", "test", "chat-1"),
		Route:     routing.RouteCODE2,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}
	if !resp.Handled {
		t.Fatal("CODE2 with Proposal should be handled via Proposal path")
	}
	if resp.Response == "" {
		t.Fatal("Expected non-empty response")
	}
	if workerService.calls != 1 {
		t.Fatalf("worker ExecuteProposal calls=%d, want 1", workerService.calls)
	}
}

func TestCodeExecutor_ModuleRegistryInjectsContextAndWorkspace(t *testing.T) {
	testProposal := proposal.NewProposal(
		"Fix STT",
		`[{"type": "file_edit", "action": "create", "target": "/home/nyukimi/RenCrow/RenCrow_STT/README.md", "content": "done"}]`,
		"Low risk",
		"Low cost",
	)
	coder2 := &mockCoderAgentWithProposal{proposal: testProposal}
	workerService := &recordingCodeWorkerExecutionService{}
	var events []codeExecutorEvent
	executor := NewDefaultCodeExecutor(nil, coder2, nil, nil, workerService, nil, func(eventType, from, to, content, route, jobID, sessionID, channel, chatID string) {
		events = append(events, codeExecutorEvent{eventType: eventType, from: from, to: to, content: content, route: route, jobID: jobID, sessionID: sessionID, channel: channel, chatID: chatID})
	}).WithModuleResolver(moduleapp.DefaultRegistry())

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "RenCrow_STT の音声入力を修正して", "test", "chat-1"),
		Route:     routing.RouteCODE2,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("ExecuteCode failed: %v", err)
	}
	if !resp.Handled {
		t.Fatal("expected proposal path")
	}
	if !strings.Contains(coder2.lastProposalInput, "RenCrow module context") ||
		!strings.Contains(coder2.lastProposalInput, "module_id: stt") ||
		!strings.Contains(coder2.lastProposalInput, "root: /home/nyukimi/RenCrow/RenCrow_STT") {
		t.Fatalf("coder did not receive module context: %s", coder2.lastProposalInput)
	}
	if strings.Contains(coder2.lastProposalInput, "install_command:") ||
		strings.Contains(coder2.lastProposalInput, "restart_target:") ||
		strings.Contains(coder2.lastProposalInput, "build, and restart") {
		t.Fatalf("coder received executable lifecycle context: %s", coder2.lastProposalInput)
	}
	if !strings.Contains(coder2.lastProposalInput, "manual approval steps") {
		t.Fatalf("coder did not receive manual-only lifecycle rule: %s", coder2.lastProposalInput)
	}
	if workerService.workspace != "/home/nyukimi/RenCrow/RenCrow_STT" {
		t.Fatalf("worker workspace=%q, want RenCrow_STT root", workerService.workspace)
	}
	if _, ok := findCodeExecutorEvent(events, "module.selected", "mio", "shiro"); !ok {
		t.Fatalf("module.selected event not emitted: %+v", events)
	}
	if _, ok := findCodeExecutorEvent(events, "worker.workspace", "shiro", "worker"); !ok {
		t.Fatalf("worker.workspace event not emitted: %+v", events)
	}
}

func TestAppendModuleContextLifecycleCommandsAreManualOnly(t *testing.T) {
	got := appendModuleContextToCodeRequest("修復して", domainmodule.Resolution{
		Module: domainmodule.Module{
			ID:             "chat",
			DisplayName:    "RenCrow_CORE",
			Root:           "/home/nyukimi/RenCrow/RenCrow_CORE",
			Kind:           "go",
			InstallCommand: "cp build/rencrow-linux-amd64 ~/.local/bin/rencrow",
			RestartTarget:  "rencrow.service",
		},
		MatchedBy:  "test",
		Confidence: 1,
	})
	if strings.Contains(got, "install_command:") || strings.Contains(got, "restart_target:") {
		t.Fatalf("module context exposed executable lifecycle commands:\n%s", got)
	}
	for _, want := range []string{"install_command_manual_only:", "restart_target_manual_only:", "manual approval steps"} {
		if !strings.Contains(got, want) {
			t.Fatalf("module context missing %q:\n%s", want, got)
		}
	}
}

func TestCodeExecutor_CODE3_WithProposalRecordsSkillChangeEvidence(t *testing.T) {
	testProposal := proposal.NewProposal(
		"Update Skill manifest",
		`diff --git a/skills/core/example/SKILL.md b/skills/core/example/SKILL.md`,
		"Low risk",
		"Low cost",
	)

	coder3 := &mockCoderAgentWithProposal{
		response: "plain response should not be used",
		proposal: testProposal,
	}
	workerService := &recordingCodeWorkerExecutionService{}
	evidence := &recordingCoderProposalEvidenceRecorder{}
	executor := NewDefaultCodeExecutor(nil, nil, coder3, nil, workerService, nil, noopEventEmitter).
		WithCoderProposalEvidenceRecorder(evidence)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "Skillの挙動を変更して", "test", "chat-1"),
		Route:     routing.RouteCODE3,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	_, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("ExecuteCode failed: %v", err)
	}
	if len(evidence.items) != 1 {
		t.Fatalf("recorded evidence count=%d, want 1", len(evidence.items))
	}
	got := evidence.items[0]
	if got.JobID != jobID.String() || got.SessionID != "sess-1" || got.Route != "CODE3" || got.Agent != "coder3" {
		t.Fatalf("unexpected evidence metadata: %#v", got)
	}
	if got.Patch != testProposal.Patch() || got.Plan != testProposal.Plan() {
		t.Fatalf("proposal evidence did not preserve patch/plan: %#v", got)
	}
	if !got.Success || !strings.Contains(got.ExecutionSummary, "成功: 1 件") {
		t.Fatalf("expected successful execution evidence, got %#v", got)
	}
}

func TestCodeExecutor_CODEDoesNotDynamicSelectCODE3(t *testing.T) {
	testProposal := proposal.NewProposal(
		"Test plan",
		`[{"type": "file_edit", "action": "create", "target": "dynamic-code3.txt", "content": "ok"}]`,
		"Low risk",
		"Low cost",
	)

	coder3 := &mockCoderAgentWithProposal{
		response: "plain response should not be used",
		proposal: testProposal,
	}

	workerService := &recordingCodeWorkerExecutionService{}
	executor := NewDefaultCodeExecutor(nil, nil, coder3, nil, workerService, nil, noopEventEmitter).WithCapabilities([]capability.CoderCapability{
		{Name: "coder3", Quality: 5, Available: true},
	})

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	_, err := executor.ExecuteCode(context.Background(), req)
	if err == nil {
		t.Fatal("expected CODE route to fail when coder1 is unavailable")
	}
	if !strings.Contains(err.Error(), "CODE route requested but coder1 is unavailable") {
		t.Fatalf("unexpected error: %v", err)
	}
	if workerService.calls != 0 {
		t.Fatalf("worker ExecuteProposal calls=%d, want 0", workerService.calls)
	}
}

func TestCodeExecutor_CODE_ReleasesCoderStatusAfterGenerateSuccess(t *testing.T) {
	status := NewCoderStatus()
	coder1 := &mockCoderAgent{response: "CODE response"}
	executor := NewDefaultCodeExecutor(coder1, nil, nil, nil, nil, status, noopEventEmitter)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}
	if resp.Response != "CODE response" {
		t.Fatalf("Response=%q, want CODE response", resp.Response)
	}
	if status.IsBusy("coder1") {
		t.Fatal("coder1 should be released after successful Generate path")
	}
}

func TestCodeExecutor_CODE_ReleasesCoderStatusAfterGenerateError(t *testing.T) {
	status := NewCoderStatus()
	coderErr := errors.New("generate failed")
	coder1 := &failingCoderAgent{err: coderErr}
	executor := NewDefaultCodeExecutor(coder1, nil, nil, nil, nil, status, noopEventEmitter)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	_, err := executor.ExecuteCode(context.Background(), req)
	if !errors.Is(err, coderErr) {
		t.Fatalf("Expected Generate error %v, got %v", coderErr, err)
	}
	if status.IsBusy("coder1") {
		t.Fatal("coder1 should be released after failed Generate path")
	}
}

func TestCodeExecutor_ExplicitRouteDoesNotUseLowerCoder(t *testing.T) {
	var events []codeExecutorEvent
	coder2 := &mockCoderAgent{response: "unexpected coder2 response"}
	executor := NewDefaultCodeExecutor(nil, coder2, nil, nil, nil, nil, recordingCodeEventEmitter(&events)).WithCapabilities([]capability.CoderCapability{
		{Name: "coder2", Quality: 4, Available: true},
	})

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE3,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	_, err := executor.ExecuteCode(context.Background(), req)
	if err == nil {
		t.Fatal("expected CODE3 to fail when coder3 is unavailable")
	}
	if !strings.Contains(err.Error(), "CODE3 route requested but no coder3 available") {
		t.Fatalf("unexpected error: %v", err)
	}
	if _, ok := findCodeExecutorEvent(events, "agent.notice", "shiro", "mio"); ok {
		t.Fatalf("explicit route must not emit degraded notice: %#v", events)
	}
}

func TestCodeExecutor_ProposalUnsupportedCoderFallsBackToGeneratePath(t *testing.T) {
	coder3 := &mockCoderAgent{response: "generate response"}
	workerService := &recordingCodeWorkerExecutionService{}
	executor := NewDefaultCodeExecutor(nil, nil, coder3, nil, workerService, nil, noopEventEmitter)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE3,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}
	if resp.Handled {
		t.Fatal("coder without proposal support should stay on Generate path, not proposal-handled")
	}
	if resp.Response != "generate response" {
		t.Fatalf("Response=%q, want generate response", resp.Response)
	}
	if workerService.calls != 0 {
		t.Fatalf("worker ExecuteProposal calls=%d, want 0", workerService.calls)
	}
}

func TestCodeExecutor_WorkerExecutionErrorIsReturnedAsError(t *testing.T) {
	workerErr := errors.New("worker failed")
	testProposal := proposal.NewProposal(
		"Test plan",
		`[{"type": "shell", "command": "echo ok"}]`,
		"Low risk",
		"Low cost",
	)
	coder3 := &mockCoderAgentWithProposal{proposal: testProposal}
	workerService := &recordingCodeWorkerExecutionService{err: workerErr}
	var events []codeExecutorEvent
	executor := NewDefaultCodeExecutor(nil, nil, coder3, nil, workerService, nil, recordingCodeEventEmitter(&events))

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE3,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err == nil {
		t.Fatal("Expected worker execution error")
	}
	if !errors.Is(err, workerErr) {
		t.Fatalf("Expected wrapped worker error %v, got %v", workerErr, err)
	}
	if resp.Response != "" || resp.Handled {
		t.Fatalf("worker error should not produce handled success response: %#v", resp)
	}
	if workerService.calls != 1 {
		t.Fatalf("worker ExecuteProposal calls=%d, want 1", workerService.calls)
	}
	event, ok := findCodeExecutorEvent(events, "agent.response", "shiro", "mio")
	if !ok {
		t.Fatal("Expected worker error event from shiro to mio")
	}
	if !strings.Contains(event.content, "実行失敗") {
		t.Fatalf("worker error event content=%q, want execution failure", event.content)
	}
}

func TestCodeExecutor_ProposalPathEmitsLanguageTrace(t *testing.T) {
	testProposal := proposal.NewProposal(
		"1. ファイルを更新する\n2. テストする",
		`[{"type": "shell", "command": "echo ok"}]`,
		"Low risk",
		"Low cost",
	)
	coder3 := &mockCoderAgentWithProposal{proposal: testProposal}
	workerService := &recordingCodeWorkerExecutionService{}
	var events []codeExecutorEvent
	executor := NewDefaultCodeExecutor(nil, nil, coder3, nil, workerService, nil, recordingCodeEventEmitter(&events))

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "TTSを直して", "viewer", "viewer-user"),
		Route:     routing.RouteCODE3,
		SessionID: "viewer",
		Channel:   "viewer",
		ChatID:    "viewer-user",
		JobID:     jobID.String(),
	}

	if _, err := executor.ExecuteCode(context.Background(), req); err != nil {
		t.Fatalf("ExecuteCode failed: %v", err)
	}

	delegate := codeExecutorEventIndex(events, "agent.delegate", "mio", "shiro")
	shiroReadback := codeExecutorEventIndex(events, "agent.acknowledge", "shiro", "mio")
	coderDelegate := codeExecutorEventIndex(events, "agent.delegate", "shiro", "coder3")
	coderReadback := codeExecutorEventIndex(events, "agent.acknowledge", "coder3", "shiro")
	coderReport := codeExecutorEventIndex(events, "agent.report", "coder3", "shiro")
	request := codeExecutorEventIndex(events, "worker.request", "shiro", "worker")
	result := codeExecutorEventIndex(events, "worker.result", "worker", "shiro")
	report := codeExecutorEventIndex(events, "agent.report", "shiro", "mio")
	if delegate < 0 || shiroReadback < 0 || coderDelegate < 0 || coderReadback < 0 || coderReport < 0 || request < 0 || result < 0 || report < 0 {
		t.Fatalf("missing language trace events: %#v", events)
	}
	if !(delegate < shiroReadback && shiroReadback < coderDelegate && coderDelegate < coderReadback && coderReadback < coderReport && coderReport < request && request < result && result < report) {
		t.Fatalf("unexpected language trace order: delegate=%d shiro_readback=%d coder_delegate=%d coder_readback=%d coder_report=%d request=%d result=%d report=%d", delegate, shiroReadback, coderDelegate, coderReadback, coderReport, request, result, report)
	}
	if !strings.HasPrefix(events[delegate].content, "Shiro、") || !strings.Contains(events[delegate].content, "会話内容") {
		t.Fatalf("Mio handoff must name Shiro and include conversation: %q", events[delegate].content)
	}
	if !strings.HasPrefix(events[shiroReadback].content, "Mio、") || !strings.Contains(events[shiroReadback].content, "復唱") {
		t.Fatalf("Shiro readback must name Mio and repeat the handoff: %q", events[shiroReadback].content)
	}
	if !strings.HasPrefix(events[coderDelegate].content, "Coder3、") || !strings.HasPrefix(events[coderReadback].content, "Shiro、") {
		t.Fatalf("Coder handoff must use named speech: delegate=%q readback=%q", events[coderDelegate].content, events[coderReadback].content)
	}
	if !strings.HasPrefix(events[coderReport].content, "Shiro、") || !strings.HasPrefix(events[report].content, "Mio、") {
		t.Fatalf("completion reports must name the delegator: coder=%q shiro=%q", events[coderReport].content, events[report].content)
	}
	if !strings.Contains(events[request].content, "Shiro内部実行器への指示") {
		t.Fatalf("worker request is not verbalized: %q", events[request].content)
	}
	if strings.Contains(events[request].content, "ShiroからWorker") {
		t.Fatalf("worker request must not describe Shiro and Worker as separate agents: %q", events[request].content)
	}
	if strings.Contains(events[request].content, "検証済みとしてWorkerで実行") {
		t.Fatalf("worker request must not claim unverified proposals are pre-validated: %q", events[request].content)
	}
	if !strings.Contains(events[request].content, "実行器側で検証") {
		t.Fatalf("worker request should require worker-side validation: %q", events[request].content)
	}
	if !strings.Contains(events[result].content, "Shiro内部実行器の戻り") {
		t.Fatalf("worker result is not verbalized: %q", events[result].content)
	}
}

func TestCodeExecutor_GenerateErrorDoesNotEmitShiroSuccess(t *testing.T) {
	generateErr := errors.New("generate failed")
	coder1 := &failingCoderAgent{err: generateErr}
	var events []codeExecutorEvent
	executor := NewDefaultCodeExecutor(coder1, nil, nil, nil, nil, nil, recordingCodeEventEmitter(&events))

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE1,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if !errors.Is(err, generateErr) {
		t.Fatalf("Expected Generate error %v, got %v", generateErr, err)
	}
	if resp.Response != "" || resp.Handled {
		t.Fatalf("Generate error should not produce fallback success response: %#v", resp)
	}
	if _, ok := findCodeExecutorEvent(events, "agent.response", "shiro", "mio"); ok {
		t.Fatalf("Generate error should not emit shiro->mio success response: %#v", events)
	}
	if _, ok := findCodeExecutorEvent(events, "agent.response", "coder1", "shiro"); !ok {
		t.Fatalf("Generate error should emit coder->shiro error evidence: %#v", events)
	}
}

func TestCodeExecutor_CODE_GenericRouteUsesOnlyCoder1(t *testing.T) {
	coder2 := &mockCoderAgent{response: "unexpected coder2 response"}

	executor := NewDefaultCodeExecutor(nil, coder2, nil, nil, nil, nil, noopEventEmitter)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	_, err := executor.ExecuteCode(context.Background(), req)
	if err == nil {
		t.Fatal("expected CODE route to fail when coder1 is unavailable")
	}
	if !strings.Contains(err.Error(), "CODE route requested but coder1 is unavailable") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestCodeExecutor_CODE_GenericRouteBlocksExternalCoder1(t *testing.T) {
	coder1 := &mockCoderAgent{response: "unexpected external response"}
	executor := NewDefaultCodeExecutor(coder1, nil, nil, nil, nil, nil, noopEventEmitter).
		WithExternalCoderPolicy(map[string]bool{"coder1": true})

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	_, err := executor.ExecuteCode(context.Background(), req)
	if err == nil {
		t.Fatal("expected CODE route to require explicit route for external coder1")
	}
	if !strings.Contains(err.Error(), "uses an external provider") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestCodeExecutor_CODE1_ExplicitRouteAllowsExternalCoder1(t *testing.T) {
	coder1 := &mockCoderAgent{response: "explicit coder1 response"}
	executor := NewDefaultCodeExecutor(coder1, nil, nil, nil, nil, nil, noopEventEmitter).
		WithExternalCoderPolicy(map[string]bool{"coder1": true})

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE1,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}
	if resp.Response != "explicit coder1 response" {
		t.Fatalf("unexpected response: %q", resp.Response)
	}
}

// ヘルパー関数
func noopEventEmitter(eventType, from, to, content, route, jobID, sessionID, channel, chatID string) {
	// テスト用の空実装
}

type failingCoderAgent struct {
	err error
}

func (m *failingCoderAgent) Generate(ctx context.Context, t task.Task, systemPrompt string) (string, error) {
	return "", m.err
}

type codeExecutorEvent struct {
	eventType string
	from      string
	to        string
	content   string
	route     string
	jobID     string
	sessionID string
	channel   string
	chatID    string
}

func recordingCodeEventEmitter(events *[]codeExecutorEvent) func(eventType, from, to, content, route, jobID, sessionID, channel, chatID string) {
	return func(eventType, from, to, content, route, jobID, sessionID, channel, chatID string) {
		*events = append(*events, codeExecutorEvent{
			eventType: eventType,
			from:      from,
			to:        to,
			content:   content,
			route:     route,
			jobID:     jobID,
			sessionID: sessionID,
			channel:   channel,
			chatID:    chatID,
		})
	}
}

func findCodeExecutorEvent(events []codeExecutorEvent, eventType, from, to string) (codeExecutorEvent, bool) {
	for _, event := range events {
		if event.eventType == eventType && event.from == from && event.to == to {
			return event, true
		}
	}
	return codeExecutorEvent{}, false
}

func codeExecutorEventIndex(events []codeExecutorEvent, eventType, from, to string) int {
	for i, event := range events {
		if event.eventType == eventType && event.from == from && event.to == to {
			return i
		}
	}
	return -1
}

type recordingCodeWorkerExecutionService struct {
	calls     int
	jobID     task.JobID
	proposal  *proposal.Proposal
	workspace string
	err       error
}

func (s *recordingCodeWorkerExecutionService) ExecuteObservation(_ context.Context, _ []service.ObservationAction) ([]service.ObservationActionResult, error) {
	return nil, nil
}

func (s *recordingCodeWorkerExecutionService) ExecuteProposal(ctx context.Context, jobID task.JobID, p *proposal.Proposal) (*patch.PatchExecutionResult, error) {
	s.calls++
	s.jobID = jobID
	s.proposal = p
	if s.err != nil {
		return nil, s.err
	}
	result := patch.NewPatchExecutionResult()
	result.AddResult(patch.CommandResult{Success: true, Output: "ok"})
	return result.WithSummary("実行: 1 件, 成功: 1 件, 失敗: 0 件"), nil
}

func (s *recordingCodeWorkerExecutionService) ExecuteProposalInWorkspace(ctx context.Context, jobID task.JobID, p *proposal.Proposal, workspace string) (*patch.PatchExecutionResult, error) {
	s.workspace = workspace
	return s.ExecuteProposal(ctx, jobID, p)
}

type recordingCoderProposalEvidenceRecorder struct {
	items []domainskill.CoderProposalEvidence
	err   error
}

func (r *recordingCoderProposalEvidenceRecorder) SaveCoderProposalEvidence(_ context.Context, item domainskill.CoderProposalEvidence) (domainskill.CoderProposalEvidencePaths, error) {
	r.items = append(r.items, item)
	if r.err != nil {
		return domainskill.CoderProposalEvidencePaths{}, r.err
	}
	return domainskill.CoderProposalEvidencePaths{
		RootPath:            "workspace/logs/skill_governance/coder_evidence/job",
		SkillDiffPath:       "workspace/logs/skill_governance/coder_evidence/job/skill_diff.md",
		AgentTranscriptPath: "workspace/logs/skill_governance/coder_evidence/job/agent_transcript.md",
	}, nil
}
