package main

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestInteractionProfileGuardEnforcesKnownClientCapabilities(t *testing.T) {
	next := http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusNoContent)
	})
	handler := withInteractionProfileGuard(next)

	tests := []struct {
		name    string
		client  string
		profile string
		method  string
		path    string
		want    int
	}{
		{
			name:   "known client requires profile",
			client: "RenCrow_PORTAL",
			method: http.MethodGet,
			path:   "/viewer/events",
			want:   http.StatusForbidden,
		},
		{
			name:    "portal chat can send",
			client:  "RenCrow_PORTAL",
			profile: "portal-chat",
			method:  http.MethodPost,
			path:    "/viewer/send",
			want:    http.StatusNoContent,
		},
		{
			name:    "portal chat can transcribe audio through CORE",
			client:  "RenCrow_PORTAL",
			profile: "portal-chat",
			method:  http.MethodPost,
			path:    "/stt/chat-input",
			want:    http.StatusNoContent,
		},
		{
			name:    "portal idlechat can read",
			client:  "RenCrow_PORTAL",
			profile: "portal-idlechat",
			method:  http.MethodGet,
			path:    "/viewer/idlechat/status",
			want:    http.StatusNoContent,
		},
		{
			name:    "portal idlechat cannot send",
			client:  "RenCrow_PORTAL",
			profile: "portal-idlechat",
			method:  http.MethodPost,
			path:    "/viewer/send",
			want:    http.StatusForbidden,
		},
		{
			name:    "portal idlechat can report surface presence",
			client:  "RenCrow_PORTAL",
			profile: "portal-idlechat",
			method:  http.MethodPost,
			path:    "/viewer/surface-presence",
			want:    http.StatusNoContent,
		},
		{
			name:    "portal idlechat can control topic stock playback",
			client:  "RenCrow_PORTAL",
			profile: "portal-idlechat",
			method:  http.MethodPost,
			path:    "/viewer/idlechat/playback",
			want:    http.StatusNoContent,
		},
		{
			name:    "portal chat can report surface presence",
			client:  "RenCrow_PORTAL",
			profile: "portal-chat",
			method:  http.MethodPost,
			path:    "/viewer/surface-presence",
			want:    http.StatusNoContent,
		},
		{
			name:    "portal chat cannot manually start idlechat",
			client:  "RenCrow_PORTAL",
			profile: "portal-chat",
			method:  http.MethodPost,
			path:    "/viewer/idlechat/start",
			want:    http.StatusForbidden,
		},
		{
			name:    "portal chat cannot control topic stock playback",
			client:  "RenCrow_PORTAL",
			profile: "portal-chat",
			method:  http.MethodPost,
			path:    "/viewer/idlechat/playback",
			want:    http.StatusForbidden,
		},
		{
			name:    "portal idlechat cannot transcribe audio through CORE",
			client:  "RenCrow_PORTAL",
			profile: "portal-idlechat",
			method:  http.MethodPost,
			path:    "/stt/chat-input",
			want:    http.StatusForbidden,
		},
		{
			name:    "portal games can launch agent session",
			client:  "RenCrow_PORTAL",
			profile: "portal-games",
			method:  http.MethodPost,
			path:    "/viewer/games/launch",
			want:    http.StatusNoContent,
		},
		{
			name:    "portal games can read observer frames",
			client:  "RenCrow_PORTAL",
			profile: "portal-games",
			method:  http.MethodGet,
			path:    "/viewer/games/observer-api/games/sessions/nh-1/frames",
			want:    http.StatusNoContent,
		},
		{
			name:    "portal games can retry session",
			client:  "RenCrow_PORTAL",
			profile: "portal-games",
			method:  http.MethodPost,
			path:    "/viewer/games/observer-api/games/sessions/nh-1/retry",
			want:    http.StatusNoContent,
		},
		{
			name:    "portal games cannot submit agent decision",
			client:  "RenCrow_PORTAL",
			profile: "portal-games",
			method:  http.MethodPost,
			path:    "/viewer/games/decision",
			want:    http.StatusForbidden,
		},
		{
			name:    "portal games cannot write observer summary",
			client:  "RenCrow_PORTAL",
			profile: "portal-games",
			method:  http.MethodPost,
			path:    "/viewer/games/observer-api/games/sessions/nh-1/summary",
			want:    http.StatusForbidden,
		},
		{
			name:    "portal games cannot transcribe audio through CORE",
			client:  "RenCrow_PORTAL",
			profile: "portal-games",
			method:  http.MethodPost,
			path:    "/stt/chat-input",
			want:    http.StatusForbidden,
		},
		{
			name:    "cmd chat can stream",
			client:  "RenCrow_CMD",
			profile: "cmd-chat",
			method:  http.MethodGet,
			path:    "/viewer/events",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd chat can transcribe audio through CORE",
			client:  "RenCrow_CMD",
			profile: "cmd-chat",
			method:  http.MethodPost,
			path:    "/stt/chat-input",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd idlechat can stop",
			client:  "RenCrow_CMD",
			profile: "cmd-idlechat",
			method:  http.MethodPost,
			path:    "/viewer/idlechat/stop",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd diagnostics can read runtime capabilities",
			client:  "RenCrow_CMD",
			profile: "cmd-diagnostics",
			method:  http.MethodGet,
			path:    "/viewer/capabilities",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd diagnostics can read profile promotion diagnostics",
			client:  "RenCrow_CMD",
			profile: "cmd-diagnostics",
			method:  http.MethodGet,
			path:    "/viewer/memory/profile-promotions",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd diagnostics can list owner memory",
			client:  "RenCrow_CMD",
			profile: "cmd-diagnostics",
			method:  http.MethodGet,
			path:    "/v1/memory/user",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd diagnostics can show owner memory",
			client:  "RenCrow_CMD",
			profile: "cmd-diagnostics",
			method:  http.MethodGet,
			path:    "/v1/memory/user/mem-1",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd diagnostics can verify parquet export",
			client:  "RenCrow_CMD",
			profile: "cmd-diagnostics",
			method:  http.MethodGet,
			path:    "/viewer/memory/export/export-request-1",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd diagnostics can read ChatGPT import status",
			client:  "RenCrow_CMD",
			profile: "cmd-diagnostics",
			method:  http.MethodGet,
			path:    "/v1/memory/import/chatgpt/export-1",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd diagnostics can read ChatGPT import progress",
			client:  "RenCrow_CMD",
			profile: "cmd-diagnostics",
			method:  http.MethodGet,
			path:    "/v1/memory/import/chatgpt/export-1/progress",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd diagnostics cannot retry profile promotions",
			client:  "RenCrow_CMD",
			profile: "cmd-diagnostics",
			method:  http.MethodPost,
			path:    "/viewer/memory/profile-promotions/retry",
			want:    http.StatusForbidden,
		},
		{
			name:    "cmd control can evaluate trade policy without execution",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodPost,
			path:    "/viewer/trade/policy/evaluate",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd control can request non-mutating trade risk preview",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodPost,
			path:    "/viewer/trade/risk-preview",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd control can explicitly commit a simulation-only fill",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodPost,
			path:    "/viewer/trade/simulation-commit",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd control can explicitly record a shadow observation",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodPost,
			path:    "/viewer/trade/shadow/observations",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd control can explicitly record a shadow outcome",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodPost,
			path:    "/viewer/trade/shadow/outcomes",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd control can explicitly record a shadow outcome review",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodPost,
			path:    "/viewer/trade/shadow/outcomes/reviews",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd control can retry failed profile promotions",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodPost,
			path:    "/viewer/memory/profile-promotions/retry",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd control can propose owner memory",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodPost,
			path:    "/v1/memory/user/propose",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd control can export parquet",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodPost,
			path:    "/viewer/memory/export/parquet",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd control can upload ChatGPT import",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodPost,
			path:    "/v1/memory/import/chatgpt",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd control can confirm ChatGPT import",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodPost,
			path:    "/v1/memory/import/chatgpt/confirm",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd control can retry ChatGPT import jobs",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodPost,
			path:    "/v1/memory/import/chatgpt/retry",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd control can finalize ChatGPT import",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodPost,
			path:    "/v1/memory/import/chatgpt/finalize",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd diagnostics cannot export parquet",
			client:  "RenCrow_CMD",
			profile: "cmd-diagnostics",
			method:  http.MethodPost,
			path:    "/viewer/memory/export/parquet",
			want:    http.StatusForbidden,
		},
		{
			name:    "cmd control cannot verify parquet export",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodGet,
			path:    "/viewer/memory/export/export-request-1",
			want:    http.StatusForbidden,
		},
		{
			name:    "cmd control cannot export an expanded parquet path",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodPost,
			path:    "/viewer/memory/export/parquet/extra",
			want:    http.StatusForbidden,
		},
		{
			name:    "cmd control can archive owner memory",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodPost,
			path:    "/viewer/memory/user/archive",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd diagnostics cannot archive owner memory",
			client:  "RenCrow_CMD",
			profile: "cmd-diagnostics",
			method:  http.MethodPost,
			path:    "/viewer/memory/user/archive",
			want:    http.StatusForbidden,
		},
		{
			name:    "cmd control cannot read archive owner memory",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodGet,
			path:    "/viewer/memory/user/archive",
			want:    http.StatusForbidden,
		},
		{
			name:    "cmd control can plan owner memory lifecycle",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodPost,
			path:    "/viewer/memory/lifecycle/plan",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd control can run owner memory lifecycle",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodPost,
			path:    "/viewer/memory/lifecycle/run",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd diagnostics cannot plan owner memory lifecycle",
			client:  "RenCrow_CMD",
			profile: "cmd-diagnostics",
			method:  http.MethodPost,
			path:    "/viewer/memory/lifecycle/plan",
			want:    http.StatusForbidden,
		},
		{
			name:    "cmd diagnostics cannot run owner memory lifecycle",
			client:  "RenCrow_CMD",
			profile: "cmd-diagnostics",
			method:  http.MethodPost,
			path:    "/viewer/memory/lifecycle/run",
			want:    http.StatusForbidden,
		},
		{
			name:    "cmd control cannot read owner memory lifecycle plan",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodGet,
			path:    "/viewer/memory/lifecycle/plan",
			want:    http.StatusForbidden,
		},
		{
			name:    "cmd control cannot read owner memory lifecycle run",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodGet,
			path:    "/viewer/memory/lifecycle/run",
			want:    http.StatusForbidden,
		},
		{
			name:    "cmd control can transition owner memory",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodPost,
			path:    "/v1/memory/user/mem-1/confirm",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd chat cannot retry failed profile promotions",
			client:  "RenCrow_CMD",
			profile: "cmd-chat",
			method:  http.MethodPost,
			path:    "/viewer/memory/profile-promotions/retry",
			want:    http.StatusForbidden,
		},
		{
			name:    "cmd agent ops can invoke the authenticated ingress",
			client:  "RenCrow_CMD",
			profile: "agent-ops",
			method:  http.MethodPost,
			path:    "/v1/agent/ops",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd agent ops cannot use another method",
			client:  "RenCrow_CMD",
			profile: "agent-ops",
			method:  http.MethodGet,
			path:    "/v1/agent/ops",
			want:    http.StatusForbidden,
		},
		{
			name:    "cmd control can read a shadow outcome report",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodGet,
			path:    "/viewer/trade/shadow/outcomes/report?study_id=study-1",
			want:    http.StatusNoContent,
		},
		{
			name:    "cmd control can read a shadow review report",
			client:  "RenCrow_CMD",
			profile: "cmd-control",
			method:  http.MethodGet,
			path:    "/viewer/trade/shadow/outcomes/reviews/report?study_id=study-1",
			want:    http.StatusNoContent,
		},
		{
			name:    "client profile pair must match",
			client:  "RenCrow_CMD",
			profile: "portal-chat",
			method:  http.MethodPost,
			path:    "/viewer/send",
			want:    http.StatusForbidden,
		},
		{
			name:    "assistant core profile can send",
			client:  "RenCrow_ASSISTANT",
			profile: "assistant-core",
			method:  http.MethodPost,
			path:    "/viewer/send",
			want:    http.StatusNoContent,
		},
		{
			name:    "assistant core profile can deliver LINE notification",
			client:  "RenCrow_ASSISTANT",
			profile: "assistant-core",
			method:  http.MethodPost,
			path:    "/internal/assistant/notifications/line",
			want:    http.StatusNoContent,
		},
		{
			name:   "assistant LINE notification requires profile headers",
			method: http.MethodPost,
			path:   "/internal/assistant/notifications/line",
			want:   http.StatusForbidden,
		},
		{
			name:   "core debug viewer remains internal",
			method: http.MethodPost,
			path:   "/viewer/send",
			want:   http.StatusNoContent,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			req := httptest.NewRequest(tt.method, tt.path, nil)
			if tt.client != "" {
				req.Header.Set("X-RenCrow-Client", tt.client)
			}
			if tt.profile != "" {
				req.Header.Set("X-RenCrow-Interaction-Profile", tt.profile)
			}
			rec := httptest.NewRecorder()

			handler.ServeHTTP(rec, req)

			if rec.Code != tt.want {
				t.Fatalf("status = %d, want %d", rec.Code, tt.want)
			}
		})
	}
}
