package viewer

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/Nyukimin/RenCrow_CORE/internal/application/orchestrator"
	modulecore "github.com/Nyukimin/RenCrow_CORE/modules/core"
)

const (
	canonicalEventComponent = "orchestrator"
	// ListByComponent has a bounded store contract. Read the full bound before
	// applying a Viewer filter so matching older events are not hidden by an
	// unfiltered limit.
	canonicalEventLogReadLimit = 1000
)

type EventLogReader interface {
	Query(context.Context, LogFilter) ([]orchestrator.OrchestratorEvent, error)
}

// CanonicalEventLog projects orchestrator events through the canonical event
// envelope store. It intentionally owns no filesystem or secondary log.
type CanonicalEventLog struct {
	store     modulecore.EventStore
	sequencer modulecore.SequencedEventAppender
}

var _ EventLogReader = (*CanonicalEventLog)(nil)
var _ interface {
	Append(orchestrator.OrchestratorEvent) error
} = (*CanonicalEventLog)(nil)

// NewCanonicalEventLog creates a Viewer event log backed by the injected
// canonical EventStore.
func NewCanonicalEventLog(store modulecore.EventStore) (*CanonicalEventLog, error) {
	if store == nil {
		return nil, fmt.Errorf("canonical event store is required")
	}
	sequencer, ok := store.(modulecore.SequencedEventAppender)
	if !ok {
		return nil, fmt.Errorf("canonical event store must own event sequencing")
	}
	return &CanonicalEventLog{store: store, sequencer: sequencer}, nil
}

// Append records one orchestrator event in the canonical envelope store.
// EventID is generated by the upstream orchestrator and preserved here. A
// valid incoming trace ID is propagated for correlation; an omitted trace ID
// receives the store-boundary root trace. Typed identities are validated
// before persistence rather than silently converted or dropped.
func (s *CanonicalEventLog) Append(event orchestrator.OrchestratorEvent) error {
	_, err := s.AppendSequenced(event)
	return err
}

// AppendSequenced persists one event and returns the canonical sequence and
// envelope identities that all downstream projections must expose.
func (s *CanonicalEventLog) AppendSequenced(event orchestrator.OrchestratorEvent) (orchestrator.OrchestratorEvent, error) {
	if s == nil || s.store == nil {
		return orchestrator.OrchestratorEvent{}, fmt.Errorf("canonical event store is required")
	}
	if s.sequencer == nil {
		return orchestrator.OrchestratorEvent{}, fmt.Errorf("canonical event store must own event sequencing")
	}
	if err := event.EventID.Validate(); err != nil {
		return orchestrator.OrchestratorEvent{}, fmt.Errorf("event_id is invalid: %w", err)
	}
	if event.EventSeq != 0 {
		return orchestrator.OrchestratorEvent{}, fmt.Errorf("event_seq must be assigned by the canonical store")
	}
	if err := validateOrchestratorEventIdentities(event); err != nil {
		return orchestrator.OrchestratorEvent{}, err
	}
	if event.TraceID == "" && (event.CausationEventID != "" || len(event.DependencyEventIDs) > 0) {
		return orchestrator.OrchestratorEvent{}, fmt.Errorf("causation and dependency event IDs require trace_id")
	}

	payload, err := marshalOrchestratorEventPayload(event)
	if err != nil {
		return orchestrator.OrchestratorEvent{}, err
	}
	traceID := event.TraceID
	var envelope modulecore.EventEnvelope
	if traceID.Validate() == nil {
		envelope = modulecore.NewEventEnvelope(traceID, event.CausationEventID, event.DependencyEventIDs, canonicalEventComponent, event.Type, orchestratorEventOccurredAt(event.Timestamp), payload)
	} else {
		envelope = modulecore.NewRootEventEnvelope(canonicalEventComponent, event.Type, orchestratorEventOccurredAt(event.Timestamp), payload)
	}
	envelope.EventID = event.EventID
	envelope.TaskID = event.TaskID
	envelope.MessageID = event.MessageID
	envelope.SessionID = event.SessionID
	envelope.TurnID = event.TurnID
	envelope.ThreadID = event.ThreadID
	if traceID.Validate() == nil {
		envelope.TraceID = traceID
	}

	persisted, err := s.sequencer.AppendSequenced(context.Background(), envelope)
	if err != nil {
		return orchestrator.OrchestratorEvent{}, fmt.Errorf("append canonical orchestrator event: %w", err)
	}
	if err := modulecore.ValidateEventEnvelope(persisted); err != nil {
		return orchestrator.OrchestratorEvent{}, fmt.Errorf("canonical event store returned invalid envelope: %w", err)
	}
	return authoritativeOrchestratorEvent(event, persisted), nil
}

// GetByEventID resolves the exact canonical event addressed by EventID.
func (s *CanonicalEventLog) GetByEventID(ctx context.Context, eventID modulecore.EventID) (orchestrator.OrchestratorEvent, bool, error) {
	if s == nil || s.store == nil {
		return orchestrator.OrchestratorEvent{}, false, fmt.Errorf("canonical event store is required")
	}
	if err := eventID.Validate(); err != nil {
		return orchestrator.OrchestratorEvent{}, false, fmt.Errorf("event_id is invalid: %w", err)
	}
	envelope, found, err := s.store.GetByID(ctx, eventID)
	if err != nil || !found {
		return orchestrator.OrchestratorEvent{}, found, err
	}
	event, ok := projectOrchestratorEvent(envelope)
	if !ok {
		return orchestrator.OrchestratorEvent{}, true, fmt.Errorf("canonical event envelope is invalid")
	}
	return event, true, nil
}

// Query reads a bounded canonical component projection, then applies the
// existing Viewer filter semantics and requested result limit.
func (s *CanonicalEventLog) Query(ctx context.Context, filter LogFilter) ([]orchestrator.OrchestratorEvent, error) {
	if s == nil || s.store == nil {
		return nil, fmt.Errorf("canonical event store is required")
	}

	envelopes, err := s.store.ListByComponent(ctx, canonicalEventComponent, canonicalEventLogReadLimit)
	if err != nil {
		return nil, fmt.Errorf("list canonical orchestrator events: %w", err)
	}
	sort.SliceStable(envelopes, func(i, j int) bool {
		return envelopes[i].EventSeq > envelopes[j].EventSeq
	})
	if len(envelopes) > canonicalEventLogReadLimit {
		envelopes = envelopes[:canonicalEventLogReadLimit]
	}

	items := make([]orchestrator.OrchestratorEvent, 0, len(envelopes))
	for _, envelope := range envelopes {
		if envelope.ComponentID != canonicalEventComponent {
			continue
		}
		event, ok := projectOrchestratorEvent(envelope)
		if !ok || !matchesLogFilter(event, filter) {
			continue
		}
		items = append(items, event)
	}
	if filter.Limit > 0 && len(items) > filter.Limit {
		items = items[:filter.Limit]
	}
	return items, nil
}

func marshalOrchestratorEventPayload(event orchestrator.OrchestratorEvent) (map[string]any, error) {
	encoded, err := json.Marshal(event)
	if err != nil {
		return nil, fmt.Errorf("encode orchestrator event payload: %w", err)
	}
	payload := make(map[string]any)
	if err := json.Unmarshal(encoded, &payload); err != nil {
		return nil, fmt.Errorf("decode orchestrator event payload: %w", err)
	}
	return payload, nil
}

func orchestratorEventOccurredAt(raw string) time.Time {
	if occurredAt, err := time.Parse(time.RFC3339Nano, strings.TrimSpace(raw)); err == nil {
		return occurredAt.UTC()
	}
	return time.Now().UTC()
}

func projectOrchestratorEvent(envelope modulecore.EventEnvelope) (orchestrator.OrchestratorEvent, bool) {
	if err := modulecore.ValidateEventEnvelope(envelope); err != nil {
		return orchestrator.OrchestratorEvent{}, false
	}
	if envelope.Payload == nil {
		return orchestrator.OrchestratorEvent{}, false
	}
	encoded, err := json.Marshal(envelope.Payload)
	if err != nil {
		return orchestrator.OrchestratorEvent{}, false
	}
	var event orchestrator.OrchestratorEvent
	if err := json.Unmarshal(encoded, &event); err != nil {
		return orchestrator.OrchestratorEvent{}, false
	}
	if event.EventID != "" {
		if err := event.EventID.Validate(); err != nil {
			return orchestrator.OrchestratorEvent{}, false
		}
	}
	if event.EventSeq < 0 {
		return orchestrator.OrchestratorEvent{}, false
	}
	if err := validateOrchestratorEventIdentities(event); err != nil {
		return orchestrator.OrchestratorEvent{}, false
	}
	// EventType is assigned in the canonical envelope and is therefore the
	// authoritative type if a stored payload was edited independently.
	if strings.TrimSpace(envelope.EventType) != "" {
		event.Type = envelope.EventType
	}
	return authoritativeOrchestratorEvent(event, envelope), true
}

func authoritativeOrchestratorEvent(event orchestrator.OrchestratorEvent, envelope modulecore.EventEnvelope) orchestrator.OrchestratorEvent {
	event.EventID = envelope.EventID
	event.EventSeq = envelope.EventSeq
	event.TraceID = envelope.TraceID
	event.CausationEventID = envelope.CausationEventID
	event.DependencyEventIDs = append([]modulecore.EventID(nil), envelope.DependencyEventIDs...)
	event.TaskID = envelope.TaskID
	event.MessageID = envelope.MessageID
	event.SessionID = envelope.SessionID
	event.TurnID = envelope.TurnID
	event.ThreadID = envelope.ThreadID
	return event
}

func validateOrchestratorEventIdentities(event orchestrator.OrchestratorEvent) error {
	identities := []struct {
		name     string
		value    string
		validate func() error
	}{
		{name: "trace_id", value: string(event.TraceID), validate: event.TraceID.Validate},
		{name: "session_id", value: string(event.SessionID), validate: event.SessionID.Validate},
		{name: "message_id", value: string(event.MessageID), validate: event.MessageID.Validate},
		{name: "turn_id", value: string(event.TurnID), validate: event.TurnID.Validate},
		{name: "thread_id", value: string(event.ThreadID), validate: event.ThreadID.Validate},
		{name: "task_id", value: string(event.TaskID), validate: event.TaskID.Validate},
	}
	for _, identity := range identities {
		if identity.value == "" {
			continue
		}
		if err := identity.validate(); err != nil {
			return fmt.Errorf("%s is invalid: %w", identity.name, err)
		}
	}
	if event.CausationEventID != "" {
		if err := event.CausationEventID.Validate(); err != nil {
			return fmt.Errorf("causation_event_id is invalid: %w", err)
		}
	}
	for _, dependencyID := range event.DependencyEventIDs {
		if err := dependencyID.Validate(); err != nil {
			return fmt.Errorf("dependency_event_id is invalid: %w", err)
		}
	}
	return nil
}

func matchesLogFilter(event orchestrator.OrchestratorEvent, filter LogFilter) bool {
	agent := strings.ToLower(strings.TrimSpace(filter.Agent))
	switch {
	case filter.EventID != "" && event.EventID != filter.EventID:
		return false
	case filter.Type != "" && !strings.EqualFold(event.Type, filter.Type):
		return false
	case agent != "" && !strings.EqualFold(event.From, agent) && !strings.EqualFold(event.To, agent):
		return false
	case filter.Route != "" && !strings.EqualFold(event.Route, filter.Route):
		return false
	case filter.TaskID != "" && event.TaskID != filter.TaskID:
		return false
	case filter.SessionID != "" && !strings.EqualFold(string(event.SessionID), filter.SessionID):
		return false
	case filter.ChatID != "" && !strings.EqualFold(event.ChatID, filter.ChatID):
		return false
	default:
		return true
	}
}
