package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"

	"github.com/Nyukimin/RenCrow_CORE/internal/adapter/config"
	"github.com/Nyukimin/RenCrow_CORE/internal/domain/agent"
	domaintransport "github.com/Nyukimin/RenCrow_CORE/internal/domain/transport"
)

// coderHandler はCoderエージェントのハンドラ
type coderHandler struct {
	agentName        string
	coderAgent       *agent.CoderAgent // Fallback agent (local config)
	proposalPrompt   string
	characterPrompts map[string]string
	globalMemory     *agent.LightMemory // 共有メモリ（SSH経由の場合は再利用）
}

func (h *coderHandler) HandleMessage(ctx context.Context, msg domaintransport.Message) (domaintransport.Message, error) {
	if err := msg.Validate(); err != nil {
		return domaintransport.Message{}, fmt.Errorf("invalid transport message: %w", err)
	}
	input, err := turnInputFromAgentMessage(msg)
	if err != nil {
		return domaintransport.Message{}, err
	}

	// Message.Context の物理 provider/model 指定は互換入力としてのみ受け取り、
	// 起動時に構成した RenCrow_LLM Gateway agent を必ず使用する。
	activeAgent := h.coderAgent
	if msg.Context != nil {
		if coderCfgRaw, ok := msg.Context["coder_config"]; ok {
			coderCfg, err := extractCoderConfig(coderCfgRaw)
			if err != nil {
				log.Printf("[coderHandler] Failed to extract CoderConfig from Context: %v", err)
			} else {
				if personality := coderPersonalityFromCharacters(coderCfg, h.characterPrompts); personality != "" {
					activeAgent.WithPersona(agent.AgentPersona{
						Name:        coderCfg.Name,
						Personality: personality,
						Tone:        coderCfg.Tone,
					})
					log.Printf("[coderHandler] Applied Persona: %s", coderCfg.Name)
				}
				if coderCfg.LightMemory.Enabled {
					if h.globalMemory == nil {
						h.globalMemory = agent.NewLightMemory(coderCfg.LightMemory.MaxTurns)
					}
					activeAgent.WithLightMemory(h.globalMemory)
					log.Printf("[coderHandler] Applied LightMemory: max_turns=%d", coderCfg.LightMemory.MaxTurns)
				}
				log.Printf("[coderHandler] Ignored physical CoderConfig provider/model; using RenCrow_LLM alias=%s", h.agentName)
			}
		}
	}

	// CoderAgentでProposal生成
	p, err := activeAgent.GenerateProposal(ctx, input)
	if err != nil {
		errResp := domaintransport.NewMessage(msg.To, msg.From, msg.SessionID, msg.TaskID,
			fmt.Sprintf("proposal generation failed: %v", err))
		errResp.Type = domaintransport.MessageTypeError
		return errResp, nil
	}

	if p == nil {
		errResp := domaintransport.NewMessage(msg.To, msg.From, msg.SessionID, msg.TaskID,
			"proposal generation returned empty result (invalid format)")
		errResp.Type = domaintransport.MessageTypeError
		return errResp, nil
	}

	response := domaintransport.NewMessage(msg.To, msg.From, msg.SessionID, msg.TaskID,
		fmt.Sprintf("Proposal generated by %s", h.agentName))
	response.Type = domaintransport.MessageTypeResult
	response.Proposal = &domaintransport.ProposalPayload{
		Plan:     p.Plan(),
		Patch:    p.Patch(),
		Risk:     p.Risk(),
		CostHint: p.CostHint(),
	}

	return response, nil
}

// extractCoderConfig は Message.Context から CoderConfig を抽出
func extractCoderConfig(raw interface{}) (config.CoderConfig, error) {
	// JSON 経由で送られてくるため、map[string]interface{} として扱う
	cfgMap, ok := raw.(map[string]interface{})
	if !ok {
		return config.CoderConfig{}, fmt.Errorf("coder_config is not a map")
	}

	// JSON として再エンコード → デコード
	jsonBytes, err := json.Marshal(cfgMap)
	if err != nil {
		return config.CoderConfig{}, fmt.Errorf("failed to marshal coder_config: %w", err)
	}

	var coderCfg config.CoderConfig
	if err := json.Unmarshal(jsonBytes, &coderCfg); err != nil {
		return config.CoderConfig{}, fmt.Errorf("failed to unmarshal coder_config: %w", err)
	}

	return coderCfg, nil
}
