package heartbeat

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"sync"
	"time"

	"github.com/Nyukimin/RenCrow_CORE/internal/domain/conversation"
	domainexecution "github.com/Nyukimin/RenCrow_CORE/internal/domain/execution"
	"github.com/Nyukimin/RenCrow_CORE/internal/domain/llm"
	"github.com/Nyukimin/RenCrow_CORE/internal/domain/routing"
	domaintask "github.com/Nyukimin/RenCrow_CORE/internal/domain/task"
	domaintool "github.com/Nyukimin/RenCrow_CORE/internal/domain/tool"
	modulecore "github.com/Nyukimin/RenCrow_CORE/modules/core"
)

// ErrHeartbeatTaskOwnerUnavailable reports that a heartbeat worker cannot be
// started because its canonical Task owner or configured Agent is missing.
var ErrHeartbeatTaskOwnerUnavailable = errors.New("heartbeat task owner unavailable")

// TaskOwner is the narrow owner boundary used by heartbeat workers. TaskIDs
// and RunIDs are issued by this owner and are never generated by Heartbeat.
type TaskOwner interface {
	Create(context.Context, domaintask.Task, domaintask.SharedRoleContext) (domaintask.Task, error)
	StartRunWithReason(context.Context, modulecore.TaskID, domaintask.RunStartReason) (domaintask.Run, error)
	Succeed(context.Context, modulecore.TaskID, string) (domaintask.Task, error)
	Fail(context.Context, modulecore.TaskID, string, []string) (domaintask.Task, error)
	Cancel(context.Context, modulecore.TaskID, string) (domaintask.Task, error)
}

const heartbeatTaskCleanupTimeout = 10 * time.Second

// WithTaskOwner configures the canonical Task/Run owner and the Agent that
// owns heartbeat execution.
func (s *HeartbeatService) WithTaskOwner(owner TaskOwner, actorID string) *HeartbeatService {
	if s == nil {
		return s
	}
	s.taskOwner = owner
	s.workerActor = strings.TrimSpace(actorID)
	return s
}

// beginWorker creates and starts one owner-backed heartbeat execution. The
// returned context carries the trusted tool scope, owner-selected execution
// identity, and the existing prompt-free LLM observation.
func (s *HeartbeatService) beginWorker(
	ctx context.Context,
	message string,
	channel string,
	externalConversationID string,
) (context.Context, conversation.TurnInput, func(error) error, error) {
	var zero conversation.TurnInput
	if s == nil || s.taskOwner == nil || strings.TrimSpace(s.workerActor) == "" {
		return nil, zero, nil, ErrHeartbeatTaskOwnerUnavailable
	}
	if ctx == nil {
		return nil, zero, nil, fmt.Errorf("heartbeat worker context is required")
	}
	if strings.TrimSpace(message) == "" {
		return nil, zero, nil, fmt.Errorf("heartbeat worker message is required")
	}

	address, err := conversation.NewChannelAddress(channel, externalConversationID)
	if err != nil {
		return nil, zero, nil, fmt.Errorf("heartbeat channel address: %w", err)
	}
	if err := rejectBoundExecutionIdentity(ctx); err != nil {
		return nil, zero, nil, err
	}

	baseCtx := ctx
	scope, foundScope := domaintool.ToolExecutionScopeFromContext(ctx)
	if foundScope {
		if err := scope.Validate(); err != nil {
			return nil, zero, nil, fmt.Errorf("heartbeat tool execution scope is invalid: %w", err)
		}
		if scope.ActorKind != domaintool.ActorKindAgent || scope.ActorID != strings.TrimSpace(s.workerActor) {
			return nil, zero, nil, fmt.Errorf("heartbeat tool execution scope actor conflicts with configured worker actor")
		}
		if scope.AuthenticationSource != domaintool.AuthenticationSourceAgentOrchestrator {
			return nil, zero, nil, fmt.Errorf("heartbeat tool execution scope is not an agent orchestrator scope")
		}
	} else {
		scope, err = domaintool.NewToolExecutionScope(
			string(modulecore.NewRequestID()),
			domaintool.ActorKindAgent,
			strings.TrimSpace(s.workerActor),
			"",
			[]string{domaintool.DataScopePublic},
			domaintool.AuthenticationSourceAgentOrchestrator,
		)
		if err != nil {
			return nil, zero, nil, fmt.Errorf("heartbeat tool execution scope: %w", err)
		}
		baseCtx = domaintool.WithToolExecutionScope(baseCtx, scope)
	}

	draft := domaintask.Task{
		// Leave TaskID blank: the owner is the sole allocator of canonical IDs.
		Title:    heartbeatTaskTitle(address.ChannelType()),
		Route:    domaintask.RouteOperations,
		Assignee: strings.TrimSpace(s.workerActor),
	}
	created, err := s.taskOwner.Create(baseCtx, draft, domaintask.SharedRoleContext{})
	if err != nil {
		return nil, zero, nil, fmt.Errorf("heartbeat task creation failed: %w", err)
	}

	var finishOnce sync.Once
	var finishErr error
	finish := func(workerErr error) error {
		finishOnce.Do(func() {
			finishErr = s.finishWorker(baseCtx, created.TaskID, workerErr)
		})
		return finishErr
	}
	failBeforeWorker := func(setupErr error) (context.Context, conversation.TurnInput, func(error) error, error) {
		return nil, zero, nil, errors.Join(setupErr, finish(setupErr))
	}

	if err := created.Validate(); err != nil {
		return failBeforeWorker(fmt.Errorf("heartbeat task owner returned invalid task: %w", err))
	}
	if created.Assignee != strings.TrimSpace(s.workerActor) {
		return failBeforeWorker(fmt.Errorf("heartbeat task owner returned task for unexpected assignee"))
	}
	if created.Route != domaintask.RouteOperations {
		return failBeforeWorker(fmt.Errorf("heartbeat task owner returned task on unexpected route %q", created.Route))
	}
	if created.Status != domaintask.StatusQueued {
		return failBeforeWorker(fmt.Errorf("heartbeat task owner returned task in unexpected status %q", created.Status))
	}

	input, err := conversation.NewTurnInput(created.TaskID, message, address)
	if err != nil {
		return failBeforeWorker(fmt.Errorf("heartbeat turn input: %w", err))
	}
	input = input.
		WithSessionID(string(modulecore.NewSessionID())).
		WithRoute(routing.RouteOPS).
		WithForcedRoute(routing.RouteOPS)
	if err := input.Validate(); err != nil {
		return failBeforeWorker(fmt.Errorf("heartbeat turn input validation: %w", err))
	}

	run, err := s.taskOwner.StartRunWithReason(baseCtx, created.TaskID, domaintask.RunStartReasonFirst)
	if err != nil {
		return failBeforeWorker(fmt.Errorf("heartbeat task run start failed: %w", err))
	}
	if err := run.Validate(); err != nil {
		return failBeforeWorker(fmt.Errorf("heartbeat task owner returned invalid run: %w", err))
	}
	if run.TaskID != created.TaskID {
		return failBeforeWorker(fmt.Errorf("heartbeat task owner returned run for unexpected task"))
	}
	if run.Assignee != strings.TrimSpace(s.workerActor) {
		return failBeforeWorker(fmt.Errorf("heartbeat task owner returned run for unexpected assignee"))
	}
	if run.Status != domaintask.RunStatusRunning {
		return failBeforeWorker(fmt.Errorf("heartbeat task owner returned run in unexpected status %q", run.Status))
	}

	workerCtx, err := domainexecution.WithIdentity(baseCtx, created.TaskID, run.RunID, input.TraceID())
	if err != nil {
		return failBeforeWorker(fmt.Errorf("heartbeat execution identity: %w", err))
	}
	workerCtx = llm.WithExecutionObservation(workerCtx, llm.ExecutionObservation{
		RequestID: modulecore.RequestID(scope.RequestID),
		TaskID:    created.TaskID,
		TraceID:   string(input.TraceID()),
		SessionID: input.SessionID(),
		Initiator: strings.TrimSpace(s.workerActor),
	})
	return workerCtx, input, finish, nil
}

func rejectBoundExecutionIdentity(ctx context.Context) error {
	if _, err := domainexecution.IdentityFromContext(ctx); err == nil {
		return fmt.Errorf("heartbeat execution identity is already bound")
	} else if err.Error() != "execution task identity is required" {
		return fmt.Errorf("heartbeat execution identity is invalid: %w", err)
	}
	return nil
}

func heartbeatTaskTitle(channel string) string {
	switch strings.ToLower(strings.TrimSpace(channel)) {
	case "heartbeat", "backlog-runner", "workstream-heartbeat":
		return "Heartbeat worker (" + strings.ToLower(strings.TrimSpace(channel)) + ")"
	default:
		return "Heartbeat worker"
	}
}

func (s *HeartbeatService) finishWorker(ctx context.Context, taskID modulecore.TaskID, workerErr error) error {
	cleanupCtx, cancel := context.WithTimeout(context.WithoutCancel(ctx), heartbeatTaskCleanupTimeout)
	defer cancel()

	var err error
	switch {
	case ctx.Err() != nil || errors.Is(workerErr, context.Canceled) || errors.Is(workerErr, context.DeadlineExceeded):
		_, err = s.taskOwner.Cancel(cleanupCtx, taskID, "heartbeat worker cancelled")
	case workerErr == nil:
		_, err = s.taskOwner.Succeed(cleanupCtx, taskID, "heartbeat worker completed")
	default:
		_, err = s.taskOwner.Fail(cleanupCtx, taskID, "heartbeat worker failed", []string{"inspect heartbeat worker failure"})
	}
	if err != nil {
		return errors.Join(ctx.Err(), fmt.Errorf("heartbeat task finalization failed: %w", err))
	}
	return ctx.Err()
}
